### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by alfredobonino** [materialos/CM12-Theme#1]
What is the licenze of this project?

**Comment by danielhickman** [comment]
The product icons are under this license quoted from materialos/Icons:

> <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/StillImage" property="dct:title" rel="dct:type">Material Design Iconography</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/materialos/Icons" property="cc:attributionName" rel="cc:attributionURL">the MOS Contributors</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

The rest of the theme I don't happen to know yet. I'll get back to you.

**Comment by anuragk47** [comment]
@danielhickman I think this issue can be closed now?

**Comment by danielhickman** [comment]
Yup.
