### ISSUE TITLE
Battery in settings FC

### ISSUE THREAD

**Issue by anuragk47** [materialos/CM12-Theme#15]
I've found that the settings app crashes when trying to open the battery submenu:

12-09 12:10:51.279 12130-12130/com.android.settings D/SubSettings: Launching fragment com.android.settings.fuelgauge.PowerUsageSummary
12-09 12:10:51.411 12130-12130/com.android.settings W/ResourceType: No package identifier when getting value for resource number 0x00000000
12-09 12:10:51.412 12130-12130/com.android.settings D/AndroidRuntime: Shutting down VM
12-09 12:10:51.414 12130-12130/com.android.settings E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.android.settings, PID: 12130
                                                                      java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.SubSettings}: android.content.res.Resources$NotFoundException: Resource ID #0x0
The rest of the submenus work fine for me.

**Comment by anuragk47** [comment]
@undu Check a new apk i will be linking here soon and tell if the battery FC is fixed

**Comment by anuragk47** [comment]
The amazing Kyle Simmons told me this:
this is why your settings on the battery are crashing 
item name="android:textColorSecondary">#ff767676</item
that's in styles
Even he doesn't know how he figured it out :P

**Comment by undu** [comment]
Just chiming in to say I'm still eager to try the apk. (tried the lastest master version, still crashes)

**Comment by anuragk47** [comment]
@undu Oh yes. I haven't forgot about it.

**Comment by anuragk47** [comment]
https://drive.google.com/file/d/0B6bIIo7bmNEBZG9zdmllTlRwa3c/view?usp=docslist_api
@undu Try this one and tell if the issue is fixed.

**Comment by undu** [comment]
It works now, thanks for your work :)

**Comment by anuragk47** [comment]
Sorry to keep you waiting on that. I will close this issue now.
