### ISSUE TITLE
"Gestures" area of CM settings app isn't themed

### ISSUE THREAD

**Issue by Techman** [materialos/CM12-Theme#2]
Only available on certain devices that have gestures, obviously. I checked it just now with my OnePlus One and that wasn't themed. I suppose this is because the gestures part of the settings app is a separate component, whether intentional or not in regards to how the theme engine treats it.

**Comment by anuragk47** [comment]
Please attach a link to your settings app apk.

**Comment by maniac103** [comment]
It's not part of Settings.apk, it's a separate one named ConfigPanel.

**Comment by anuragk47** [comment]
@maniac103 What is the package name that requires to be themed in order to theme the gestures area?

**Comment by maniac103** [comment]
It's com.cyanogenmod.settings.device. See https://github.com/CyanogenMod/android_device_oppo_common/blob/cm-12.1/configpanel/AndroidManifest.xml

**Comment by anuragk47** [comment]
Fixed with commit  82a0184. Thank you @maniac103 and Kyle Simmons.
