### ISSUE TITLE
Fix Facebook Theme

### ISSUE THREAD

**Issue by anuragk47** [materialos/CM12-Theme#45]
- [ ] Fix background color too light, same as posts
- [ ] Fix FCs on both lp and mm
- [ ] Try to implement animations for reactions to post
- [ ] Replace more drawables to MD if possible and also fix some drawables' size
- [ ] Try to implement ripple animation in tabs

**Comment by HiFIi** [comment]
@Anonymas in my Android theme, I implemented ripple drawables for the Facebook tabs about 11 months ago. Here: https://github.com/I-am-Reinvented/SQR/tree/1.0.0-wip/theme/src/main/assets/overlays/com.facebook.katana/res

**Comment by anuragk47** [comment]
Thanks Kyler! I'll have a look at those.

**Comment by HiFIi** [comment]
Cool man. :) the end product really adds that extra "oomph" and looks really good.  Or as good as one can make Facebook look as it currently stands lol
