### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by ghost** [materialos/CM12-Theme#5]
I've nocticed a few odd behaviors, first the status bar is too dark in Themes app:

![screenshot_2015-12-03-18-40-10](https://cloud.githubusercontent.com/assets/6850125/11568828/b374545a-99ee-11e5-8c4d-f104d1c83c2f.png)

Then action bar from File Manager app becomes pink in Recents apps panel:

![screenshot_2015-12-03-18-40-36](https://cloud.githubusercontent.com/assets/6850125/11568905/0ff009fe-99ef-11e5-856c-01c2608abfee.png)

Thanks for this beautiful theme :+1:

**Comment by anuragk47** [comment]
@danielhickman @crutchcorn @porasjeet What do you say on the status bar in theme chooser app? Too dark? Also, what do the guidelines say.

**Comment by ghost** [comment]
For compare here is a screenshot from Settings app, the darkness on status bar is correct:

![screenshot_2015-12-08-11-50-57](https://cloud.githubusercontent.com/assets/6850125/11654475/3934975c-9da6-11e5-8fea-60cd0ac342dc.png)

By the way about Theme Chooser app, color should be blue like in Settings, right?

**Comment by anuragk47** [comment]
@M2ck I was just confirming things. About Theme Chooser it was intentionally made a different color to make the theme more colorful.

**Comment by ghost** [comment]
Ok thanks for the confirmation.

**Comment by anuragk47** [comment]
@Porasjeet what do you say about the theme chooser status bar? And the file manager recents color is also the color of switches in its settings, so it won't be changed.

**Comment by mmkiir** [comment]
Yeah, theme chooser status bar color is a little dark. And I guess we can
set different colors for switches and recent in file manager.  (Btw why is
that in this issue?)

**Comment by anuragk47** [comment]
Will be fixed with issue #25
