### ISSUE TITLE
Scrolling through the Android Settings menu is extremely slow

### ISSUE THREAD

**Issue by Xinayder** [materialos/CM12-Theme#69]
After the new update where the color for the settings mrnu changed, when you scroll it scrolls really slow, looking like your phone is using too much resources. After switching back to the default theme, the menu scrolling is back to normal.

Phone: Moto X 2014
Android Version: 6.0.1
CyanogenMod Version: 13 (20160422)

**Comment by anuragk47** [comment]
Yes. Trying to fix the issue asap.

**Comment by anuragk47** [comment]
Try new apk from play store

**Comment by Xinayder** [comment]
The new version made it faster, but the menu scrolling is still a bit slow
compared to the default one.

**Comment by anuragk47** [comment]
I tested on a few devices and saw no lag at all. Can you confirm?

**Comment by anuragk47** [comment]
I am closing this issue for now. If the issue persists, make a new issue. I need to close this for the v1.7.1 milestone.

**Comment by Xinayder** [comment]
I'm still having issues even after updating to 20160426.
When I go to the Device or Personal sections, scrolling becomes slow, but only in these sections.

**Comment by anuragk47** [comment]
We are trying to implement the settings theme in another way. That should fix the issue.
