### ISSUE TITLE
Fix theme chooser theme.

### ISSUE THREAD

**Issue by anuragk47** [materialos/CM12-Theme#70]
New theme chooser with present theme looks weird. Needs to be fixed soon.
- [x] Light nav drawer
- [ ] Header image (probably extract the art image from Google Calendar or ask Nils to make one)
- [ ] Try to implement header image on every version of theme chooser
- [x] New color scheme which looks better than the current pink
- [x] Replace drawer icons with ones from google's material design icons

**Comment by anuragk47** [comment]
Some progress with 159e43c 
TODO:
- [ ] Use Nils' drawer image
- [ ] Try to implement same drawer in CM12.1 as on CM13

**Comment by mmkiir** [comment]
I'll implement the drawer image in cm12. Leave it on me.

**Comment by anuragk47** [comment]
Okay @Porasjeet.
