### ISSUE TITLE
Try to implement settings theme via .9.png to see if it makes it smoother

### ISSUE THREAD

**Issue by anuragk47** [materialos/CM12-Theme#75]
Personally, I don't see any lag in settings. But we should try to do this.

**Comment by anuragk47** [comment]
Closing this as well since I really don't see lag in settings. Will open again if someone reports.

**Comment by Skrilltrax** [comment]
Hey There ,

Hello I'm Aditya And I'm Making A CM 13 Theme and Since Your Theme Is Open
Source , I Would Like To Use Yours As A Base. Just Asking If I Have
Permission To Do So.

Regards
Aditya Wasan

**Comment by crutchcorn** [comment]
Just make sure you follow the license. This includes listing our project and linking to it on the description, and in the app itself.
