### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by RohanVilloth** [materialos/CM12-Theme#76]
![fdroidnewheader](https://cloud.githubusercontent.com/assets/3755396/14794935/d66b49d4-0b43-11e6-8158-c6eccd15114a.png)

[F-Droid](https://f-droid.org) is an Android App Store exclusively for **open source** apps. See F-Droid's [Wikipedia page](https://en.wikipedia.org/wiki/F-Droid). You can browse the catalog of available apps on [Fossdroid](https://fossdroid.com). Some open souce icon packs and themes are already available in F-Droid: [Numix](https://fossdroid.com/a/numix-circle.html), [Theia](https://fossdroid.com/a/theia-icon-theme.html) and [available CM12 themes](https://fossdroid.com/s/cm12.html).

Users choosing to avoid Google's proprietary libraries and those with AOSP based ROMs find the F-Droid option very useful. So, I request MaterialOS CM12 theme (and icons too if possible) be made available on the F-Droid store. :relaxed:

**Comment by anuragk47** [comment]
Thoughts @danielhickman , @crutchcorn ?

**Comment by deadbaed** [comment]
looks like a nice idea!

**Comment by crutchcorn** [comment]
Absolutely! I'd love to take helm on this, but I'm currently preoccupied. @danielhickman, mind taking the reigns on this one?

**Comment by anuragk47** [comment]
Okay, I'll upload the theme on F-Droid but only the major versions (1.8 to 1.9 and not 1.8.1 or 1.8.2) starting from probably 1.8. What about the icon pack app @danielhickman @crutchcorn ?

**Comment by RohanVilloth** [comment]
@Anonymas  Why upload multiple versions? :confused: Isn't uploading the latest version enough? Is it for compatibility with CM12, 12.1 and 13 separately?

I'll file a separate issue for the [Android icon pack](https://github.com/materialos/Android-Icon-Pack) so that both could be completed independently! :relaxed:

**Comment by anuragk47** [comment]
I was not talking of multiple versions, just saying that I'll skip some of the minor updates and only publish them on the play store, but I'll make sure F-droid has a stable and new version as well. For example, a minor update to 1.7 like 1.7.1 would only go on play store but 1.8 makes it to play store, f-droid and cyngn store as well. (Since uploading everywhere is a bit of work, haha)

**Comment by RohanVilloth** [comment]
@Anonymas K.. got it now! :relaxed: Well, once an app is accepted on F-Droid, I think it could be set to autobuild from source repos for future updates. Generally, F-Droid users wouldn't mind getting beta and bleeding edge versions of their apps. :smiley:

**Comment by anuragk47** [comment]
Okay sure. Closing this issue now.

**Comment by RohanVilloth** [comment]
@Anonymas Umm.. Why is this issue closed? :confused:  Isn't it better to close it when MaterialOS is released or submitted to F-Droid?

**Comment by anuragk47** [comment]
Well. I'd upload from next version anyways. But to serve as a reminder, reopening this issue.

**Comment by est31** [comment]
Okay, I have added the app's metadata to the f-droid app store: https://gitlab.com/fdroid/fdroiddata/commit/3b834c9fd44c346aeab008fb6884732e50892d6f

It should be built by the buildbot and be available from the client within the next 24 hours.

**Comment by est31** [comment]
@HEXcube nice issue header/introductory text. Do you mind if I use it in my own issues?

**Comment by RohanVilloth** [comment]
> Okay, I have added the app's metadata to the f-droid app store: https://gitlab.com/fdroid/fdroiddata/commit/3b834c9fd44c346aeab008fb6884732e50892d6f
> 
> It should be built by the buildbot and be available from the client within the next 24 hours.

Cool! :smiley: 

> @HEXcube nice issue header/introductory text. Do you mind if I use it in my own issues?

@est31  No problem! U can use it anywhere. I hereby license this issue header text under CC 0 :wink:

**Comment by RohanVilloth** [comment]
Yay! MaterialOS in now on F-Droid. :smiley: Thank u @est31 for uploading the package to F-Droid ! :kissing_heart: 

- [On F-Droid](https://f-droid.org/repository/browse/?fdid=com.materialos.cm.theme)
- [See Link on Fossdroid](https://fossdroid.com/a/materialos.html)

**Comment by est31** [comment]
Sadly there were some issues and it got disabled and almost got forgotten, but I resurrected it. Usually it doesn't take that long :)

You are welcome!
